package com.ovwe.ticket.dao.public;

import com.ovwe.ticket.model.public.Ticket;
import com.ovwe.ticket.model.public.TicketExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    long countByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int deleteByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int insertSelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    List<Ticket> selectByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    Ticket selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Ticket record, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int updateByExample(@Param("record") Ticket record, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int updateByPrimaryKeySelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.ticket
     *
     * @mbg.generated Fri Jan 25 16:20:14 CST 2019
     */
    int updateByPrimaryKey(Ticket record);
}