package com.ovwe.ticket.dao.ticket;

import com.ovwe.ticket.model.ticket.Ticket;
import com.ovwe.ticket.model.ticket.TicketExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component(value = "TicketMapper")
@Mapper
public interface TicketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    long countByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int deleteByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int deleteByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int insert(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int insertSelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    List<Ticket> selectByExample(TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    Ticket selectByPrimaryKey(String uid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") Ticket record, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int updateByExample(@Param("record") Ticket record, @Param("example") TicketExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int updateByPrimaryKeySelective(Ticket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket.ticket
     *
     * @mbg.generated Mon Jan 28 09:23:44 CST 2019
     */
    int updateByPrimaryKey(Ticket record);

    int insertList(List<Ticket> records);
}